id = "zed-restclient"
name = "Zed REST Client"
version = "0.1.0"
schema_version = 1
authors = ["Daniel Roisch"]
description = "A REST Client for Zed, inspired by vscode-restclient."
repository = "https://github.com/doani/zed-restclient"
